Pandas - DataFrame and Series

Pandas is a powerful data manipulation library in python , widely used for data anaylsis and data cleaning. It provides two primary data structures . A series is a one-dimensional array -like object , while a DataFrame is a two-dimensional  , size-mutable , and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\raman\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\raman\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\raman\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\raman\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\raman\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\raman\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd

In [4]:
## Series
## Pandas Series is a  one-dimensional array - like object that can hold any data type . It is similar to a column in a table.

data = [1,2,3,4,5]
series = pd.Series(data)
print('series \n',series)

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
##  Create  a Series from dictionary
data = {'a':1,'b':2,'c':3}
series_dict =pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [7]:
data = [10,20,30]
index = [1,2,3]
pd.Series(data , index = index)

1    10
2    20
3    30
dtype: int64

In [9]:
# DataFrame
## Create a DataFrame from a dictionary of list

data = {
    'Name':['Raman','Sachin','Jack'],
    'Age' : [22,24,45],
    'City' : ['Delhi','New York','Florida']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age      City
0   Raman   22     Delhi
1  Sachin   24  New York
2    Jack   45   Florida
<class 'pandas.core.frame.DataFrame'>

In [10]:
import numpy as np
np.array(df)

array([['Raman', 22, 'Delhi'],
       ['Sachin', 24, 'New York'],
       ['Jack', 45, 'Florida']], dtype=object)

In [13]:
## Create a Data frame from a list of Dictionaries

data = [
    {'Name':'Raman','Age':22,'City':'Delhi'},
    {'Name':'Jack','Age':32,'City':'Delhi'},
    {'Name':'Bappy','Age':42,'City':'Delhi'},
    {'Name':'Tom','Age':52,'City':'Delhi'},
]
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age   City
0  Raman   22  Delhi
1   Jack   32  Delhi
2  Bappy   42  Delhi
3    Tom   52  Delhi
<class 'pandas.core.frame.DataFrame'>

In [14]:
df

    Name  Age   City
0  Raman   22  Delhi
1   Jack   32  Delhi
2  Bappy   42  Delhi
3    Tom   52  Delhi

In [15]:
## ACcessing a specified element
df['Name']

0    Raman
1     Jack
2    Bappy
3      Tom
Name: Name, dtype: object

In [20]:
df.at[2,'Name']

'Bappy'

In [21]:
## Accessing a specified element using iat
df.iat[2,2]

'Delhi'

In [22]:
### Data Manipulation with DataFrame
df

    Name  Age   City
0  Raman   22  Delhi
1   Jack   32  Delhi
2  Bappy   42  Delhi
3    Tom   52  Delhi

In [23]:
## Adding a new column
df['Salary'] = [50000,60000,70000,80000]

In [24]:
df

    Name  Age   City  Salary
0  Raman   22  Delhi   50000
1   Jack   32  Delhi   60000
2  Bappy   42  Delhi   70000
3    Tom   52  Delhi   80000

In [27]:
## Remove a column
df.drop('Salary',axis=1)

    Name  Age   City
0  Raman   22  Delhi
1   Jack   32  Delhi
2  Bappy   42  Delhi
3    Tom   52  Delhi

In [28]:
df

    Name  Age   City  Salary
0  Raman   22  Delhi   50000
1   Jack   32  Delhi   60000
2  Bappy   42  Delhi   70000
3    Tom   52  Delhi   80000

In [29]:
df.drop('Salary',axis = 1, inplace = True)
df

    Name  Age   City
0  Raman   22  Delhi
1   Jack   32  Delhi
2  Bappy   42  Delhi
3    Tom   52  Delhi

In [30]:
df

    Name  Age   City
0  Raman   22  Delhi
1   Jack   32  Delhi
2  Bappy   42  Delhi
3    Tom   52  Delhi

In [32]:
## Add age to the columns
df['Age']=df['Age']+1
df

    Name  Age   City
0  Raman   24  Delhi
1   Jack   34  Delhi
2  Bappy   44  Delhi
3    Tom   54  Delhi

In [34]:
df.drop(0,inplace = True)

In [35]:
df

    Name  Age   City
1   Jack   34  Delhi
2  Bappy   44  Delhi
3    Tom   54  Delhi